config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'bokes#index'
  resources :bokes, only: [:index, :new, :create, :preview] do
    collection do
      post 'preview'
      get 'done'
    end
  end
  resources :odais, only: [:index, :new, :create, :preview] do
    resources :bokes
    collection do
      post 'preview'
      get 'done'
    end
  end
  resources :photos, only: [:index, :new, :create, :upload]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boke.rb
class Boke < ApplicationRecord
  belongs_to :user
  belongs_to :odai
  has_many :comments

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :boke
  belongs_to :user
  validates :star, presence: true
end

app/models/odai.rb
class Odai < ApplicationRecord
  belongs_to :photo
  has_many :bokes
  has_many :comments, through: :bokes
  belongs_to :user
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_one :odai
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :photos
         has_many :odais
         has_many :comments
         has_many :bokes
         validates :account_name, {presence: true}
         validates :sex, {presence: true}
         validates :prefecture, {presence: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private
    def configure_permitted_parameters
      added_attrs = [ :birthday, :prefecture, :sex, :nickname, :account_name, :profile, :password ]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
      devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
    end
 end

app/controllers/bokes_controller.rb
class BokesController < ApplicationController
  before_action :authenticate_user!

  def index
    @bokes = Boke.all.order(created_at: "desc")
    @latest_boke = Boke.last
    @latest_odai = Odai.last
    @now = Time.now
    
  end
  def new
    @odai = Odai.find(params[:odai_id])
  end
  def preview
    @odai = Odai.find(params[:boke][:odai_id])
    @boke = Boke.new(
      odai_id: @odai.id,
      user_id: current_user.id,
      text: boke_params[:text],
      tag: boke_params[:tag],
      category: boke_params[:category]
    )
    render :new if @boke.invalid?
  end
  def create
    @odai = Odai.find(params[:boke][:odai_id])
    @boke = Boke.new(
      odai_id: @odai.id,
      user_id: current_user.id,
      text: boke_params[:text],
      tag: boke_params[:tag],
      category: boke_params[:category]
    )
    if @boke.save
      redirect_to done_bokes_path
    else
      redirect_to new_odai_boke_path
    end
  end


  private
  def boke_params
    params.require(:boke).permit(:text, :tag, :category)
  end

end

app/controllers/odais_controller.rb
class OdaisController < ApplicationController
  def index
    @odais = Odai.all.order(created_at: 'DESC')
  end
  def new
    @photo = Photo.order(params[:photo_id]).last
  end
  def preview
    @photo = Photo.order(params[:photo_id]).last
    @odai = Odai.new(
          title: odai_params[:title],
          tag: odai_params[:tag],
          category: odai_params[:category],
          right: odai_params[:right],
          user_id: current_user.id,
          photo_id: @photo.id
    )
    render :new if @odai.invalid?
  end
  def create
    @photo = Photo.order(params[:photo_id]).last
    @odai = Odai.new(
      title: odai_params[:title],
      tag: odai_params[:tag],
      category: odai_params[:category],
      right: odai_params[:right],
      user_id: current_user.id,
      photo_id: @photo.id
    )
    if @odai.save
      redirect_to done_odais_path
    else
      redirect_to new_odai_path
    end
  end

  private
  def odai_params
    params.require(:odai).permit(:title, :tag, :category, :right)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = Photo.all.order(created_at: "desc")
  end
  def new
  end
  def create
    @photo = Photo.new(image: photo_params[:image], user_id: current_user.id)
    @photo.save
    redirect_to new_odai_path(@photo)
    redirect_to new_photo_path unless @photo.save
  end

  def upload
  end

  private
  def photo_params
    params.require(:photo).permit(:image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bokes_helper.rb
module BokesHelper
end

app/helpers/odais_helper.rb
module OdaisHelper
end

app/views/bokes/done.html.erb
<%= image_tag 'boke_neko.png' %>
<div class="">
  ボケの投稿が完了しました。
</div>
<div class="">
  サイト上に反映されるまで少し時間がかかる可能性があります。
</div>

<div class="content__main--middle__more-button">
  <%= link_to "新着ボケへ", bokes_path %>
</div>

app/views/bokes/index.html.erb
  <div class="content">
    <div class="content--top">
        <ul>
          <li>トップ</li>
          <li>注目</li>
          <li>人気</li>
          <li>コラボ</li>
          <li>セレクト</li>
          <li>ピックアップ</li>
          <li>殿堂入り</li>
        </ul>
    </div>
    <div class="content__main">
      <div class="content__main--index-title">
        人気ボケ
      </div>
      <% if @latest_boke.present? %>
        <div class="content__main--top">
          <div class="content__main--top__boke">
            <div class="content__main--top__boke--photo">
              <%= image_tag @latest_boke.odai.photo.image %>
                <div class="content__main--top__boke--photo--content">
                  <div class="content__main--top__boke-photo--content__photoby">photo by <%= @latest_boke.odai.photo.user.nickname %> / odai by <%= @latest_boke.odai.user.nickname%></div>
                </div>
            </div>
          </div>
        </div>
        <div class="content__main--top__boke-text">
          <%= @latest_boke.text %>
        </div>
      <% end %>
      <div class="content__main--top__meta">
        <ul class="content__main--top__meta--info">
          <li class="content__main--top__meta--info__stars"><i class="fa fa-star" aria-hidden="true"></i>星の数</li>
          <li class="content__main--top__meta--info__date"><%= ((@now - @latest_boke.created_at)/60).to_i %>分くらい前</li>
          <li class="content__main--top__meta--info__list"><i class="fa fa-facebook-square" aria-hidden="true"></i></li>
          <li class="content__main--top__meta--info__list"><i class="fa fa-twitter-square" aria-hidden="true"></i></li>
          <li class="content__main--top__meta--info__list"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i></li>
          <li class="content__main--top__meta--info__list"><i class="fa fa-user-times" aria-hidden="true"></i></li>
          <li class="content__main--top__meta--info__list"><i class="fa fa-external-link" aria-hidden="true"></i></li>
        </ul>
        <div class="content__main--top__meta--rating">
          <div class="content__main--top__meta--rating__star"><i class="fa fa-star-o fa-lg boke-rating-star" aria-hidden="true"></i></div>
          <div class="content__main--top__meta--rating__star"><i class="fa fa-star-o fa-lg boke-rating-star" aria-hidden="true"></i></div>
          <div class="content__main--top__meta--rating__star"><i class="fa fa-star-o fa-lg boke-rating-star" aria-hidden="true"></i></div>
        </div>
      </div>
      <div class="content__main--middle__more-button">
        もっと見る
      </div>
      <div class="content__main--index-title">
        注目ボケ
      </div>
      <div class="content__main--middle">
        <div class="content__main--middle__boke-horizon">
          1
        </div>
        <div class="content__main--middle__boke-horizon">
          2
        </div>
        <div class="content__main--middle__boke-horizon">
          3
        </div>
        <div class="content__main--middle__boke-horizon">
          4
        </div>
        <div class="content__main--middle__boke-horizon">
          5
        </div>
        <div class="content__main--middle__boke-horizon">
          6
        </div>
        <div class="content__main--middle__more-button">
          もっと見る
        </div>
      </div>
      <div class="content__main--index-title">
        新着ボケ
      </div>
      <div class="content__main--middle">
        <div class="content__main--middle__boke-horizon">
          1
        </div>
        <div class="content__main--middle__boke-horizon">
          2
        </div>
        <div class="content__main--middle__boke-horizon">
          3
        </div>
        <div class="content__main--middle__boke-horizon">
          4
        </div>
        <div class="content__main--middle__boke-horizon">
          5
        </div>
        <div class="content__main--middle__boke-horizon">
          6
        </div>
        <div class="content__main--middle__more-button">
          もっと見る
        </div>
      </div>
    </div>
    <div class="content__right">
      <img src="https://bokete.jp/images/legend_banner.png" alt="">
      <img src="https://bokete.jp/images/keyword_banner.png" alt="">
      <img src="https://bokete-photo-gamma.s3.amazonaws.com/images/side/banner_bde6709188ea4ba1585d8ea46b93ed7d.jpg" alt="">
      <img src="https://bokete.jp/images/news_title.png" alt="">
      <div class="">
        殿堂入りボケ
      </div>

      <div class="">
        <img src="https://bokete.jp/images/app_banner_apple.png" alt="">
      </div>
      <div class="">
        <img src="https://bokete.jp/images/app_banner_google.png" alt="">
      </div>
    </div>
  </div>

  <footer class="footer">
    <div class="footer__menue">
      ボケを見る
      <ul>
        <li class="footer__menue--list">殿堂入り</li>
        <li class="footer__menue--list">人気ボケ</li>
        <li class="footer__menue--list">注目ボケ</li>
        <li class="footer__menue--list">新着ボケ</li>
        <li class="footer__menue--list">セレクト</li>
        <li class="footer__menue--list">ピックアップ</li>
      </ul>
    </div>
    <div class="footer__menue">
      ボケを探す
      <ul>
        <li class="footer__menue--list">人気のタグから探す</li>
        <li class="footer__menue--list">キーワードから探す</li>
      </ul>
    </div>
    <div class="footer__menue">
      ご利用について
      <ul>
        <li class="footer__menue--list">プライバシーポリシー</li>
        <li class="footer__menue--list">ご利用規約</li>
        <li class="footer__menue--list"ヘルプ・よくある質問></li>
        <li class="footer__menue--list">お問合わせ</li>
        <li class="footer__menue--list">広告掲載について</li>
      </ul>
    </div>
    <div class="footer__menue">
      会社情報
      <ul>
        <li class="footer__menue--list">運営会社</li>
      </ul>
    </div>
    <div class="footer__menue--copy-right">
      Copyright © ボケて（bokete）All rights reserved. 株式会社オモロキ
    </div>
  </footer>








<div class="link">link</div>
<%= link_to "お題", odais_path %>

app/views/bokes/new.html.erb
<div class="">
  boke new
</div>

<div class="">
  <%= image_tag @odai.photo.image %>
</div>
<%= form_for :boke, url: preview_bokes_path do |f| %>
  <%= f.hidden_field :odai_id, value: params[:odai_id] %>


  <div class="field">
    <%= f.label :ボケテキスト %><br />
    <%= f.text_field :text, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :タグ %><br />
    <%= f.text_field :tag, autofocus: true %>
  </div>
  <div class="field">
    <div class="">カテゴリ(*必須)  </div>
    <%= f.radio_button :category, value="バカ" %>
    <%= f.label :バカ %>
    <%= f.radio_button :category, value="シュール" %>
    <%= f.label :シュール %>
    <%= f.radio_button :category, value="お下劣" %>
    <%= f.label :お下劣 %>
    <%= f.radio_button :category, value="ブラック" %>
    <%= f.label :ブラック %>
    <%= f.radio_button :category, value="身内" %>
    <%= f.label :身内 %>
    <%= f.radio_button :category, value="例え" %>
    <%= f.label :例え %>
    <%= f.radio_button :category, value="その他" %>
    <%= f.label :その他 %>
  </div>
  <div class="">
    アダルトコンテンツ・下ねたを含むボケを投稿する場合はカテゴリーに「お下劣」を必ず指定してください
  </div>

  <%= f.submit value: "確認画面へ"%>
<% end %>

app/views/bokes/preview.html.erb
<div class="">
  お題の確認
</div>

<%= form_for :boke, url: bokes_path do |f| %>
  <%= f.hidden_field :odai_id %>
  <%= f.hidden_field :text %>
  <%= f.hidden_field :tag %>
  <%= f.hidden_field :category %>

  <div class="">
    <%= image_tag @odai.photo.image %>
  </div>


  <div class="field">
    <%= f.label :ボケテキスト %><br />
    <%= @boke.text %>
  </div>
  <div class="field">
    <%= f.label :タグ %><br />
    <%= @boke.tag%>
  </div>
  <div class="field">
    <div class="">カテゴリ(*必須)  </div>
      <%= @boke.category %>
    </div>

  <div class="">
     著作権・肖像権の侵害に当たる画像や暴力的、卑猥な画像の投稿は禁止しております。 詳しくは利用規約をご覧ください。
  </div>

  <%= f.submit value: "確認画面へ"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bokete5</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="container">
    <div class="navbar">
      <%= link_to image_tag('https://bokete.jp/images/logo.png', class: "navbar__logo"), root_path%>
      <div class="navbar__list">
        <div class="navbar__list--left">
          <div class="navbar__list--left__item"><%= link_to "ボケ", bokes_path, {class: "navbar__list--left__item--link"} %></div>
          <div class="navbar__list--left__item"><%= link_to "お題", odais_path, {class: "navbar__list--left__item--link"} %></div>
          <div class="navbar__list--left__item"><%= link_to "職人", bokes_path, {class: "navbar__list--left__item--link"} %></div>
        </div>
        <div class="navbar__list--right">
          <% if user_signed_in? %>
            <div class="navbar__list--right__item"><%= link_to current_user.nickname,  bokes_path, {class: "navbar__list--right__item--link"} %></div>
            <div class="navbar__list--right__item"><%= link_to "マイページ", odais_path, {class: "navbar__list--right__item--link"} %></div>
          <% else %>
            <div class="navbar__list--right__item"><%= link_to "新規登録",  new_user_registration_path, {class: "navbar__list--right__item--link"} %></div>
            <div class="navbar__list--right__item"><%= link_to "ログイン", new_user_session_path, {class: "navbar__list--right__item--link"} %></div>
          <% end %>
          <div class="navbar__list--right__item"><%= link_to "ヘルプ", bokes_path, {class: "navbar__list--right__item--link"} %></div>
        </div>
      </div>
    </div>
  </div>
  <body>
    <div class="container">
      <div class="top-news">
        <div class="top-news__current-place">
          <img class="top-news__current-place--image" src="https://bokete.jp/images/show_image.png" alt="">
          <span>ボケて（bokete）トップ</span>
        </div>
        <div class="top-news__right">
          <div class="top-news__right--item">ボケ投稿数</div>
          <div class="top-news__right--item">お題投稿数</div>
          <div class="top-news__right--item"><span>safe on<span></div>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
    <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p>
    <p><%= link_to "ホーム", root_path %></p>

  <% end %>
</html>

app/views/odais/done.html.erb
<%= image_tag 'boke_neko.png' %>
<div class="">
  お題の投稿が完了しました。
</div>
<div class="">
  サイト上に反映されるまで少し時間がかかる可能性があります。
</div>

<div class="content__main--middle__more-button">
  <%= link_to "新着お題へ", odais_path %>
</div>

app/views/odais/index.html.erb
<% @odais.each do |odai| %>
  <%= link_to image_tag(odai.photo.image), new_odai_boke_path(odai.id)%>
<% end %>


<div class="">
  <%= link_to "お題投稿", new_photo_path %>
</div>

app/views/odais/new.html.erb
<div class="">
  お題の投稿
</div>

<%= form_for :odai, url: preview_odais_path do |f| %>
  <div class="">
    <%= image_tag @photo.image %>
  </div>


  <div class="field">
    <%= f.label :タイトル %><br />
    <%= f.text_field :title, autofocus: true %>
  </div>
  <div class="field">
    <%= f.label :タグ %><br />
    <%= f.text_field :tag, autofocus: true %>
  </div>
  <div class="field">
    <div class="">カテゴリ(*必須)  </div>
    <%= f.radio_button :category, value="人物" %>
    <%= f.label :人物 %>
    <%= f.radio_button :category, value="人物2人以上" %>
    <%= f.label :人物2人以上 %>
    <%= f.radio_button :category, value="動物" %>
    <%= f.label :動物 %>
    <%= f.radio_button :category, value="風景" %>
    <%= f.label :風景 %>
    <%= f.radio_button :category, value="イラスト" %>
    <%= f.label :イラスト %>
    <%= f.radio_button :category, value="その他" %>
    <%= f.label :その他 %>
  </div>
  <div class="field">
    <div class="">この画像はあなたが著作権または投稿に必要な権利を有しているものですか？</div>
    <%= f.radio_button :right, value="はい" %>
    <%= f.label :はい %>
    <%= f.radio_button :right, value="いいえ" %>
    <%= f.label :いいえ %>
  </div>

  <div class="">
     著作権・肖像権の侵害に当たる画像や暴力的、卑猥な画像の投稿は禁止しております。 詳しくは利用規約をご覧ください。
  </div>

  <%= f.submit value: "確認画面へ"%>
<% end %>

app/views/odais/preview.html.erb
<div class="">
  お題の確認
</div>

<%= form_for :odai, url: odais_path do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :tag %>
  <%= f.hidden_field :category %>
  <%= f.hidden_field :right %>

  <div class="">
    <%= image_tag @odai.photo.image %>
  </div>


  <div class="field">
    <%= f.label :タイトル %><br />
    <%= @odai.title %>
  </div>
  <div class="field">
    <%= f.label :タグ %><br />
    <%= @odai.tag%>
  </div>
  <div class="field">
    <div class="">カテゴリ(*必須)  </div>
      <%= @odai.category %>
  </div>

  <div class="">
     著作権・肖像権の侵害に当たる画像や暴力的、卑猥な画像の投稿は禁止しております。
  </div>

  <%= f.submit '戻る', name: 'back'%>
  <%= f.submit "投稿する" %>
<% end %>

app/views/odais2/new.html.erb
<div class="">
  お題の投稿
</div>

<%= form_for :odai, url: photo_odais_path do |f| %>
<div class="">
  <%= image_tag @photo.image %>
</div>


<div class="field">
  <%= f.label :タイトル %><br />
  <%= f.text_field :title, autofocus: true %>
</div>
<div class="field">
  <%= f.label :タグ %><br />
  <%= f.text_field :tag, autofocus: true %>
</div>
<div class="field">
  <div class="">カテゴリ(*必須)  </div>
  <%= f.radio_button :category, value="人物" %>
  <%= f.label :人物 %>
  <%= f.radio_button :category, value="人物2人以上" %>
  <%= f.label :人物2人以上 %>
  <%= f.radio_button :category, value="動物" %>
  <%= f.label :動物 %>
  <%= f.radio_button :category, value="風景" %>
  <%= f.label :風景 %>
  <%= f.radio_button :category, value="イラスト" %>
  <%= f.label :イラスト %>
  <%= f.radio_button :category, value="その他" %>
  <%= f.label :その他 %>

</div>
<div class="field">
  <div class="">この画像はあなたが著作権または投稿に必要な権利を有しているものですか？</div>
  <%= f.radio_button :right, value="はい" %>
  <%= f.label :はい %>
  <%= f.radio_button :right, value="いいえ" %>
  <%= f.label :いいえ %>
</div>

<div class="">
   著作権・肖像権の侵害に当たる画像や暴力的、卑猥な画像の投稿は禁止しております。 詳しくは利用規約をご覧ください。
</div>

<%= f.submit value: "確認画面へ"%>
<% end %>

app/views/photos/create.html.erb
<div class="">
  投稿が完了しました。
</div>
<div class="">
  <%= image_tag @photo.image %>
</div>

app/views/photos/index.html.erb
<div class="">
  PhotosController
</div>
<div class="">
  お題投稿
</div>

<a href="https://bokete.jp/images/odai-post-01.jpg"></a>


<div class="">
  flickrからお題を選ぶ

</div>
<button type="submit" name="submit"></button>



<%= link_to "手持ちの写真をお題に", new_photo_path %>
<button type="submit" name="submit"></button>

app/views/photos/new.html.erb
<div class="">
  手持ちの写真からお題を投稿する
</div>

<!-- <div class="">
  <input type="img" name="img" value="1.ファイルを選択">
</div>
<div class="">
  <input type="submit" name="img" value="1.ファイルをアップロード">
</div> -->

<%= form_for :photo, url: photos_path do |f| %>
  <div class="" >
    <div class="">
      <!-- <%= f.label :img do %>
      <% end %> -->
    <div class="">
      <%= f.file_field :image, value: "1.ファイルを選択する" %>
    </div>
    </div>

    <div class="">
      <%= f.submit "2.ファイルをアップロード" %>
    </div>
  </div>
<% end %>